package com.example.wallet.controller;

import com.example.wallet.audit.AuditService;
import com.example.wallet.dto.request.CreateUserRequest;
import com.example.wallet.dto.request.UpdateIssueStatusRequest;
import com.example.wallet.dto.request.UserStatusUpdateRequest;
import com.example.wallet.dto.response.*;
import com.example.wallet.enums.ActivityType;
import com.example.wallet.enums.IssueStatus;
import com.example.wallet.enums.LedgerEntryType;
import com.example.wallet.enums.UserStatus;
import com.example.wallet.repository.LedgerEntryRepository;
import com.example.wallet.repository.TransactionIssueRepository;
import com.example.wallet.repository.TransactionRepository;
import com.example.wallet.repository.UserRepository;
import com.example.wallet.repository.WalletRepository;
import com.example.wallet.security.CustomUserDetails;
import com.example.wallet.service.IssueService;
import com.example.wallet.service.TransactionService;
import com.example.wallet.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;

@RestController
@RequestMapping("/api/v1/admin")
@PreAuthorize("hasAuthority('ROLE_ADMIN')")
@RequiredArgsConstructor
@Tag(name = "Admin Operations", description = "Endpoints for user management, system metrics, transaction ledger oversight, and issue resolution")
public class AdminController {

    private final UserService userService;
    private final TransactionService transactionService;
    private final IssueService issueService;
    private final AuditService auditService;

    private final UserRepository userRepository;
    private final WalletRepository walletRepository;
    private final TransactionRepository transactionRepository;
    private final LedgerEntryRepository ledgerEntryRepository;
    private final TransactionIssueRepository issueRepository;

    @GetMapping("/dashboard")
    @Operation(summary = "Get system-wide health and financial KPI metrics")
    public ResponseEntity<ApiResponse<AdminDashboardMetricsResponse>> getDashboardMetrics() {
        long totalUsers = userRepository.count();
        long activeUsers = userRepository.countByStatus(UserStatus.ACTIVE);
        long inactiveUsers = userRepository.countByStatus(UserStatus.INACTIVE);
        long totalWallets = walletRepository.count();
        long totalTxns = transactionRepository.count();
        BigDecimal totalVolume = transactionRepository.calculateTotalSuccessfulVolume();
        BigDecimal totalCredit = ledgerEntryRepository.sumTotalByEntryType(LedgerEntryType.CREDIT);
        BigDecimal totalDebit = ledgerEntryRepository.sumTotalByEntryType(LedgerEntryType.DEBIT);
        long openIssues = issueRepository.countByStatus(IssueStatus.OPEN) + issueRepository.countByStatus(IssueStatus.IN_PROGRESS);

        AdminDashboardMetricsResponse metrics = AdminDashboardMetricsResponse.builder()
                .totalUsers(totalUsers)
                .activeUsers(activeUsers)
                .inactiveUsers(inactiveUsers)
                .totalWallets(totalWallets)
                .totalTransactions(totalTxns)
                .totalVolume(totalVolume)
                .totalCredit(totalCredit)
                .totalDebit(totalDebit)
                .openIssues(openIssues)
                .build();

        return ResponseEntity.ok(ApiResponse.success(metrics));
    }

    // --- User Management ---

    @GetMapping("/users")
    @Operation(summary = "Search and list all users")
    public ResponseEntity<ApiResponse<Page<UserResponse>>> getUsers(
            @RequestParam(required = false) String query,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Page<UserResponse> users = userService.getAllUsers(query, PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt")));
        return ResponseEntity.ok(ApiResponse.success(users));
    }

    @PostMapping("/users")
    @Operation(summary = "Create user with autogenerated temporary credentials and automatic wallet creation")
    public ResponseEntity<ApiResponse<UserResponse>> createUser(@Valid @RequestBody CreateUserRequest request) {
        UserResponse response = userService.createUser(request);
        return ResponseEntity.ok(ApiResponse.success("User and wallet created successfully", response));
    }

    @GetMapping("/users/{id}")
    @Operation(summary = "Get user details by ID")
    public ResponseEntity<ApiResponse<UserResponse>> getUserById(@PathVariable Long id) {
        UserResponse response = userService.getUserById(id);
        return ResponseEntity.ok(ApiResponse.success(response));
    }

    @PatchMapping("/users/{id}/status")
    @Operation(summary = "Activate or deactivate a user and their wallet")
    public ResponseEntity<ApiResponse<UserResponse>> updateUserStatus(
            @AuthenticationPrincipal CustomUserDetails admin,
            @PathVariable Long id,
            @Valid @RequestBody UserStatusUpdateRequest request) {
        UserResponse response = userService.updateUserStatus(admin.getId(), id, request.getStatus());
        return ResponseEntity.ok(ApiResponse.success("User status updated to " + request.getStatus(), response));
    }

    @PostMapping("/users/{id}/reset-password")
    @Operation(summary = "Generate new temporary credentials for a user")
    public ResponseEntity<ApiResponse<UserResponse>> resetUserCredentials(
            @AuthenticationPrincipal CustomUserDetails admin,
            @PathVariable Long id) {
        UserResponse response = userService.resetUserCredentials(admin.getId(), id);
        return ResponseEntity.ok(ApiResponse.success("Temporary credentials generated successfully", response));
    }

    // --- Transactions & Ledger ---

    @GetMapping("/transactions")
    @Operation(summary = "List and search all system transactions")
    public ResponseEntity<ApiResponse<Page<TransactionResponse>>> getTransactions(
            @RequestParam(required = false) String query,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Page<TransactionResponse> pageResult = transactionService.getAllTransactions(query, PageRequest.of(page, size));
        return ResponseEntity.ok(ApiResponse.success(pageResult));
    }

    @GetMapping("/transactions/{reference}")
    @Operation(summary = "Inspect transaction with full double-entry ledger debit/credit breakdown")
    public ResponseEntity<ApiResponse<TransactionResponse>> getTransactionDetails(
            @AuthenticationPrincipal CustomUserDetails admin,
            @PathVariable String reference) {
        TransactionResponse response = transactionService.getTransactionByReference(reference, admin.getId(), true);
        return ResponseEntity.ok(ApiResponse.success(response));
    }

    // --- Issues Desk ---

    @GetMapping("/issues")
    @Operation(summary = "List and filter issues")
    public ResponseEntity<ApiResponse<Page<IssueResponse>>> getIssues(
            @RequestParam(required = false) IssueStatus status,
            @RequestParam(required = false) String query,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Page<IssueResponse> issues = issueService.getAllIssues(status, query, PageRequest.of(page, size));
        return ResponseEntity.ok(ApiResponse.success(issues));
    }

    @PatchMapping("/issues/{id}")
    @Operation(summary = "Update issue status (OPEN -> IN_PROGRESS -> RESOLVED) and add resolution notes")
    public ResponseEntity<ApiResponse<IssueResponse>> updateIssue(
            @AuthenticationPrincipal CustomUserDetails admin,
            @PathVariable Long id,
            @Valid @RequestBody UpdateIssueStatusRequest request) {
        IssueResponse response = issueService.updateIssueStatus(admin.getId(), id, request);
        return ResponseEntity.ok(ApiResponse.success("Issue updated successfully", response));
    }

    // --- Audit Logs ---

    @GetMapping("/audit-logs")
    @Operation(summary = "Query audit trail logs")
    public ResponseEntity<ApiResponse<Page<AuditLogResponse>>> getAuditLogs(
            @RequestParam(required = false) ActivityType activityType,
            @RequestParam(required = false) String query,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {
        Page<AuditLogResponse> logs = auditService.getAuditLogs(activityType, query, PageRequest.of(page, size));
        return ResponseEntity.ok(ApiResponse.success(logs));
    }
}
