package com.example.wallet.enums;

public enum ActivityType {
    USER_CREATED,
    USER_LOGIN,
    LOGIN_FAILED,
    PASSWORD_RESET,
    WALLET_CREATED,
    WALLET_ACTIVATED,
    WALLET_DEACTIVATED,
    MONEY_ADDED,
    TRANSFER_CREATED,
    TRANSFER_SUCCESS,
    TRANSFER_FAILED,
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_RESOLVED,
    ADMIN_ACTION
}
